### ISSUE TITLE
What does the answer index signifies?

### ISSUE THREAD

**Issue by ritwikmishra** [erzaliator/HindiRC-Data#1]
Does it signify the sentence number from which the factoid answer is extracted?

**Comment by erzaliator** [comment]
The table in [README.md](https://github.com/erzaliator/HindiRC-Data/blob/master/README.md) states the details. And yes, answer index tag (\<l\>) specifies the index of the answer sentence in the passage. The raw text of the answer sentence is also mentioned in the "answer" tag (\<a\>).

In our [paper](https://www.researchgate.net/publication/342424208_HindiRC_A_Dataset_for_Reading_Comprehension_in_Hindi), **we report the Textual Similarity task metrics based on the \<l\> tag**. Please note, while the task was made on single sentence answers, for future research the complete answer's indices are also stored in the " Multi sentence answer index tag" \<lg\>. Please refer to Section 3.3 for more details on how we made single sentence answers.
