### ISSUE TITLE
How accuracy is calculated?

### ISSUE THREAD

**Issue by ritwikmishra** [erzaliator/HindiRC-Data#2]
Do you mean Exact Match (EM) ? Because that is a widely used metric in QnA

**Comment by erzaliator** [comment]
For each <q,a_i> pair where q is a question and a_i is sampled from the set of candidate answers we calculate S_i = score(q,a_i) where scores could be BM25, Word Overlap, etc. The <q,a_i> that returns the highest score is chosen as the predicted answer. We check if the predicted answer and the actual answer are an **Exact Match** or not and report the accuracy.

I hope that answers your question.
